### PR TITLE
Add Arabic Language

### PR DESCRIPTION
**Pull request by bashayerAlsalman**
Thank you for the amazing work !
I added the translation of countries in Arabic language baed on the default language of the device.

### CODE REVIEW

**Comment by mukeshsolanki** [comment]
Arabic support is not needed

**Comment by bashayerAlsalman** [comment]
Why?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mukeshsolanki** [comment]
localization is not generic. Not everyone would want to use the localized version. Libraries are supposed to be more generic.

**Comment by bashayerAlsalman** [comment]
Good point, thanks for answering

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
